# docker-compose.yml

version: '3.3'

services:

  venftserver:
    image: deerajdocker/veframework.docker.venftappserver
    container_name: venftappserver
    depends_on:
      - ipfs
      - nebliod
    ports:
      - "8090:80"

  nebliod:
    #image: neblioteam/nebliod
    build: ./nebliod
    container_name: neblio
    volumes:
      - $HOME/neblio-data:/root/.neblio
      #- ./nebliod/files/neblio.conf:~/.neblio/neblio.conf
    ports:
      - "6325:6325"
      - "6326:6326"

  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-kubo
    volumes:
      - ./home/ipfs/data:/data/ipfs
      - ./home/ipfs/staging:/export
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"
