---
- hosts: 13.66.21.18
  tasks:
    - name: Install dependencies
      apt:
        name:
          - tar
          - unzip
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3
      become: yes

    - name: Create actions-runner directory
      file:
        path: actions-runner
        state: directory

    - name: Download runner package
      get_url:
        url: "https://github.com/actions/runner/releases/download/v2.304.0/actions-runner-linux-x64-2.304.0.tar.gz"
        dest: actions-runner/actions-runner-linux-x64-2.304.0.tar.gz

    - name: Extract runner package
      shell: |
        cd actions-runner
        tar -xzf actions-runner-linux-x64-2.304.0.tar.gz
        cd ..
        chown -R veframework:veframework actions-runner
      become: yes

    - name: Configure the runner
      shell: |
        cd actions-runner
        ./config.sh --unattended --url {{ url }} --token {{ token }} --replace [--name {{ name }}]

    - name: Register the service
      shell: |
        cd actions-runner
        ./svc.sh install {{ username }}
      become: yes

    - name: Start the service
      shell: |
        cd actions-runner
        ./svc.sh start
      become: yes
