name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Build and push Docker image
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: .
      #    push: true
      #    tags: your-registry/your-image-name:latest
      #  env:
      #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy Docker Compose file
        run: |
          cp docker-compose.yml /home/veframework/docker-compose.yml

      - name: SSH into Azure VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 22.121.140.71
          username: veframework
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker-compose -f /home/veframework/docker-compose.yml up
